#!/usr/bin/env bash
# Template-internal gate (CDT-54 / CDT-46-C8): hook bodies SoT =
# skills/init-orchestration/SKILL.md fenced templates (plus commands/tdd-gate.md
# for tdd-gate) only.
#
# Default (no args): for each managed hook, extract the fenced block that
# follows its marker and verify template-internal hygiene:
#   - marker + fenced block present and extractable
#   - non-empty body
#   - shebang line
#   - bash -n parse clean
#   - shellcheck --shell=bash clean, strict when shellcheck is installed
#     (SPEC-030 R33): any finding, or a bare `# shellcheck disable=` with no
#     trailing reason, fails the gate; one fail-open note when absent
# Covers the 8 HOOKS names plus tdd-gate (wp-1-10-gate-hooks C1).
#
# --extract <name>: prints the fenced body verbatim (one trailing newline) to
# stdout and exits 0. This is the single extractor CLI (wp-1-10-gate-hooks
# D15/C1) — every caller that needs a hook/fence body (test suites,
# check-hook-templates itself) goes through this flag, never a second
# hand-rolled extraction.
#
# Does NOT require package-tracked live `.claude/hooks/*.sh` (generated by
# /setup orchestration; dual-copy retired per SPEC-002/SPEC-005/SPEC-010).
#
# Wired into /release as Step 4.7. Run from any cwd.

set -uo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
SKILL="$ROOT/skills/init-orchestration/SKILL.md"
TDD_GATE_MD="$ROOT/commands/tdd-gate.md"

HOOKS="task-completed stop-review memory-capture bash-compress precompact-rescue rescue-pointer friction-capture escalation-gate"

if [ ! -f "$SKILL" ]; then
  echo "check-hook-templates: SKILL.md not found at $SKILL" >&2
  exit 1
fi

# extract_fence FILE MARKER INFO
#   Prints the body of the first ```<INFO> fence found after the first
#   occurrence of MARKER in FILE, with no trailing newline. Exits 0 on
#   success. Exits 3, with exactly one stderr line, when FILE cannot be
#   read, MARKER is not found, or no fence with exactly info-string INFO
#   follows it before the next line that is exactly ```.
extract_fence() {
  local file="$1" marker="$2" info="$3"
  FILE="$file" MARKER="$marker" INFO="$info" python3 -c '
import os, re, sys

path = os.environ["FILE"]
marker = os.environ["MARKER"]
info = os.environ["INFO"]

try:
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
except OSError as e:
    sys.stderr.write("check-hook-templates: cannot read %s: %s\n" % (path, e))
    sys.exit(3)

idx = text.find(marker)
if idx == -1:
    sys.stderr.write("check-hook-templates: marker not found in %s: %r\n" % (path, marker))
    sys.exit(3)

rest = text[idx:]
pattern = re.compile(r"\n```" + re.escape(info) + r"\n(.*?)\n```(?:\n|$)", re.DOTALL)
m = pattern.search(rest)
if not m:
    sys.stderr.write("check-hook-templates: no fenced ```%s block after marker in %s\n" % (info, path))
    sys.exit(3)

sys.stdout.write(m.group(1))
'
}

# do_extract NAME
#   Resolves NAME against the C1 name table and calls extract_fence.
#   Returns 64 for an unrecognized NAME (no stderr — callers report it),
#   otherwise returns extract_fence's rc (0 or 3) with body on stdout.
do_extract() {
  local name="$1"
  case "$name" in
    task-completed|stop-review|memory-capture|bash-compress|precompact-rescue|rescue-pointer|friction-capture|escalation-gate)
      extract_fence "$SKILL" "create \`.claude/hooks/${name}.sh\` with this content:" "bash"
      return $?
      ;;
    tdd-gate)
      extract_fence "$TDD_GATE_MD" "create \`.claude/hooks/tdd-gate.sh\` with this content:" "bash template"
      return $?
      ;;
    seed-db)
      extract_fence "$SKILL" "**If DB exists:** use the \`Bash\` tool to run the python3 sqlite3 insert:" "bash"
      return $?
      ;;
    seed-baseline)
      extract_fence "$SKILL" "#### Baseline memory content" "markdown"
      return $?
      ;;
    *)
      return 64
      ;;
  esac
}

# sc_fail_add NAME
#   Records NAME once in SC_FAIL (a template can trip both the bare-disable
#   rule and the shellcheck run).
sc_fail_add() {
  case " $SC_FAIL " in
    *" $1 "*) ;;
    *) SC_FAIL="$SC_FAIL $1" ;;
  esac
}

if [ "${1:-}" = "--extract" ]; then
  NAME="${2:-}"
  if [ -z "$NAME" ]; then
    echo "check-hook-templates: --extract requires a <name>" >&2
    exit 64
  fi
  BODY=$(do_extract "$NAME")
  RC=$?
  if [ "$RC" -eq 64 ]; then
    echo "check-hook-templates: unknown extract name '$NAME'" >&2
    exit 64
  elif [ "$RC" -ne 0 ]; then
    exit 3
  fi
  printf '%s\n' "$BODY"
  exit 0
fi

FAILED=()
SC_FAIL=""
WORKDIR=$(mktemp -d "${TMPDIR:-/tmp}/check-hook-templates.XXXXXX")
trap 'rm -rf "$WORKDIR"' EXIT

for name in $HOOKS tdd-gate; do
  extracted=$(do_extract "$name" 2>/dev/null)
  rc=$?
  if [ "$rc" -ne 0 ]; then
    if [ "$name" = "tdd-gate" ]; then src_label="commands/tdd-gate.md"; else src_label="SKILL.md"; fi
    echo "check-hook-templates: could not extract template for '$name' from $src_label" >&2
    FAILED+=("$name (template not extractable)")
    continue
  fi

  if [ -z "$extracted" ]; then
    echo "check-hook-templates: empty template body for '$name'" >&2
    FAILED+=("$name (empty body)")
    continue
  fi

  # First non-empty line must be a bash shebang (hook scripts are bash).
  first=$(printf '%s\n' "$extracted" | sed -n '/./{p;q;}')
  case "$first" in
    '#!/usr/bin/env bash'|'#!/bin/bash'|'#!/usr/bin/bash') ;;
    *)
      echo "check-hook-templates: '$name' template missing bash shebang (got: ${first:-<empty>})" >&2
      FAILED+=("$name (no shebang)")
      continue
      ;;
  esac

  out="$WORKDIR/${name}.sh"
  printf '%s\n' "$extracted" > "$out"
  if ! bash -n "$out" 2>"$WORKDIR/${name}.n.err"; then
    echo "check-hook-templates: '$name' template fails bash -n:" >&2
    cat "$WORKDIR/${name}.n.err" >&2 || true
    FAILED+=("$name (bash -n)")
    continue
  fi

  # SPEC-030 R33/AC2: strict when shellcheck is present. Any finding fails
  # the gate (full output per offending template, uncapped since CDT-502 T1;
  # an rc >= 2 from shellcheck itself is fail-closed too). A bare
  # `# shellcheck disable=` — no trailing reason after the code list — fails
  # as well (R33, same present-only pass). Without shellcheck the pass is
  # skipped with one fail-open note (CDT-286).
  if command -v shellcheck >/dev/null 2>&1; then
    bare=$(printf '%s\n' "$extracted" | awk '
      {
        rest = $0
        if (rest !~ /^[[:space:]]*#[[:space:]]*shellcheck[[:space:]]+disable=/) next
        sub(/^[[:space:]]*#[[:space:]]*shellcheck[[:space:]]+disable=/, "", rest)
        while (1) {
          s = rest
          sub(/^[[:space:]]+/, "", s)
          rest = s
          if (rest ~ /^SC[0-9]+/) { sub(/^SC[0-9]+/, "", rest); continue }
          if (rest ~ /^all([^[:alnum:]]|$)/) { sub(/^all/, "", rest); continue }
          if (sub(/^,/, "", rest)) { continue }
          break
        }
        if (rest ~ /^[[:space:]]*$/) print NR
      }
    ')
    if [ -n "$bare" ]; then
      bare="${bare//$'\n'/ }"
      echo "check-hook-templates: '$name' template has a bare 'shellcheck disable=' (no trailing reason) at template line(s): $bare (SPEC-030 R33)" >&2
      sc_fail_add "$name"
    fi
    if ! shellcheck --shell=bash --severity=warning "$out" > "$WORKDIR/${name}.sc.err" 2>&1; then
      echo "check-hook-templates: '$name' template has shellcheck --shell=bash findings:" >&2
      cat "$WORKDIR/${name}.sc.err" >&2 || true
      sc_fail_add "$name"
    fi
  else
    SHELLCHECK_SKIPPED=1
  fi
done

if [ -n "$SC_FAIL" ]; then
  echo "check-hook-templates: FAIL — shellcheck gate (strict, SPEC-030 R33):$SC_FAIL" >&2
  RC=1
else
  RC=0
fi

if [ "${SHELLCHECK_SKIPPED:-0}" = "1" ]; then
  echo "check-hook-templates: note: shellcheck not installed — the template shellcheck pass was skipped (fail-open, CDT-286)" >&2
fi

if [ "${#FAILED[@]}" -gt 0 ]; then
  echo "check-hook-templates: FAIL — template hygiene issue(s): ${FAILED[*]}" >&2
  RC=1
fi
if [ "$RC" -ne 0 ]; then
  exit "$RC"
fi

echo "check-hook-templates: OK — ${HOOKS// /, }, tdd-gate templates extractable + bash -n clean (SoT: skills/init-orchestration/SKILL.md, commands/tdd-gate.md)"
exit 0
