#!/usr/bin/env bash
# Template-internal gate (CDT-54 / CDT-46-C8): hook bodies SoT =
# skills/init-orchestration/SKILL.md fenced templates only.
#
# For each managed hook, extract the fenced ```bash block that follows the
#   "create `.claude/hooks/<name>.sh` with this content:" marker in SKILL.md,
# and verify template-internal hygiene:
#   - marker + fenced block present and extractable
#   - non-empty body
#   - shebang line
#   - bash -n parse clean
#
# Does NOT require package-tracked live `.claude/hooks/*.sh` (generated by
# /setup orchestration; dual-copy retired per SPEC-002/SPEC-005/SPEC-010).
#
# Wired into /release as Step 4.7. Run from any cwd.

set -uo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
SKILL="$ROOT/skills/init-orchestration/SKILL.md"

HOOKS="task-completed stop-review memory-capture bash-compress precompact-rescue rescue-pointer friction-capture"
if [ ! -f "$SKILL" ]; then
  echo "check-hook-templates: SKILL.md not found at $SKILL" >&2
  exit 1
fi

FAILED=()
WORKDIR=$(mktemp -d "${TMPDIR:-/tmp}/check-hook-templates.XXXXXX")
trap 'rm -rf "$WORKDIR"' EXIT

for name in $HOOKS; do
  extracted=$(SKILL="$SKILL" NAME="$name" python3 -c '
import os, sys, re
skill = open(os.environ["SKILL"], encoding="utf-8").read()
name = os.environ["NAME"]
marker = "create `.claude/hooks/%s.sh` with this content:" % name
idx = skill.find(marker)
if idx == -1:
    sys.stderr.write("no marker for %s\n" % name)
    sys.exit(3)
rest = skill[idx:]
m = re.search(r"\n```bash\n(.*?)\n```", rest, re.DOTALL)
if not m:
    sys.stderr.write("no fenced bash block after marker for %s\n" % name)
    sys.exit(3)
# Emit block content WITHOUT a trailing newline; we re-add exactly one below.
sys.stdout.write(m.group(1))
' 2>/dev/null)
  rc=$?
  if [ "$rc" -ne 0 ]; then
    echo "check-hook-templates: could not extract template for '$name' from SKILL.md" >&2
    FAILED+=("$name (template not extractable)")
    continue
  fi

  if [ -z "$extracted" ]; then
    echo "check-hook-templates: empty template body for '$name'" >&2
    FAILED+=("$name (empty body)")
    continue
  fi

  # First non-empty line must be a bash shebang (hook scripts are bash).
  first=$(printf '%s\n' "$extracted" | sed -n '/./{p;q;}')
  case "$first" in
    '#!/usr/bin/env bash'|'#!/bin/bash'|'#!/usr/bin/bash') ;;
    *)
      echo "check-hook-templates: '$name' template missing bash shebang (got: ${first:-<empty>})" >&2
      FAILED+=("$name (no shebang)")
      continue
      ;;
  esac

  out="$WORKDIR/${name}.sh"
  printf '%s\n' "$extracted" > "$out"
  if ! bash -n "$out" 2>"$WORKDIR/${name}.n.err"; then
    echo "check-hook-templates: '$name' template fails bash -n:" >&2
    cat "$WORKDIR/${name}.n.err" >&2 || true
    FAILED+=("$name (bash -n)")
    continue
  fi
done

if [ "${#FAILED[@]}" -gt 0 ]; then
  echo "check-hook-templates: FAIL — template hygiene issue(s): ${FAILED[*]}" >&2
  exit 1
fi

echo "check-hook-templates: OK — ${HOOKS// /, } templates extractable + bash -n clean (SoT: skills/init-orchestration/SKILL.md)"
exit 0
